---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: binarydata/debian-jessie

suites:
  - name: default
    run_list:
      - recipe[docker::default]
    attributes:
      docker:
        users:
         - vagrant
