---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: ./roles

platforms:
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - role[base]
      - role[scala-deploy-default]
      - role[scala-deploy-custom]
