name             'thin'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures thin'
long_description 'Installs/Configures thin'
version          '0.1.4'

depends 'docker', '~> 0.0.8'
depends 'report'
